name: solara_mobile
description: PureTune 音乐播放器 - 移动客户端
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # HTTP
  dio: ^5.4.0

  # 状态管理
  provider: ^6.1.1

  # 音频播放
  just_audio: ^0.9.46
  audio_service: ^0.18.18
  rxdart: ^0.27.7

  # 本地存储
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_colorpicker: ^1.0.3

  # 工具
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.2
  intl: ^0.19.0

  # 本地文件选择
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
